### ISSUE TITLE
Question about rectification result

### ISSUE THREAD

**Issue by KondziuK** [uzh-rpg/DSEC#16]
Hello, 
I`ve been trying to visualize rectified events by using rectification maps that you provided but I ended with some strange blank lines (upper images) in contrast to normal visualization (lower images). Did I miss some operations that I have to provide first?

Thanks a lot,
Konrad
![Rectyfication](https://user-images.githubusercontent.com/27052231/119974478-fcba0500-bfb4-11eb-926b-e24af315493b.PNG)

**Comment by magehrig** [comment]
Hi @KondziuK 

How are you visualizing the rectified events here? Are you performing nearest neighbor assignment of the rectified pixel coordinates or performing interpolation?

**Comment by KondziuK** [comment]
Hi @magehrig
Iam using nearest neigbor - I am casting rectified coordinates to int. I`ve perform rectification like this:
_data = Sequence(seq_path,mode=mode,delta_t_ms=delt_t_ms, num_bins=num_bins)
rectify_map_left = data.rectify_events(data.event_slicers['left'].events['x'][:], data.event_slicers['left'].events['y'][:], 'left')
data.event_slicers['left'].events['x'] = rectify_map_left[:, 0]
data.event_slicers['left'].events['y'] = rectify_map_left[:, 1]_

To visualize I`ve used slighty changed EventReader class and render function with new polarity assigment:
    _mask1 = (x>=0)&(y>=0)&(W>x)&(H>y)
    p_new = p[mask1]
    mask[y[mask1],x[mask1]]=p_new_

**Comment by magehrig** [comment]
Yet another possibility is to use backward warping as explained in another issue: https://github.com/uzh-rpg/DSEC/issues/14#issuecomment-841348958

**Comment by magehrig** [comment]
Let me know if the issue still persists. I am closing this issue for now.

**Comment by KondziuK** [comment]
Hi,
Yes, the issue still exists. I tried to implement render function basing on the equation that you provided but I am stuck. I am ending with very big values in interp_weights and I don`t know how then map them into values {-1,0,1} just as it was in function render. I tried to experiment with adding mask like it was in render function but still no good results. Here is the function that I tried somehow to create:

    
    def render2(x ,y , pol , H, W):
      x0 = x.astype(int)
      y0 = y.astype(int)
      img = np.full((H,W,3), fill_value=255,dtype='uint8')
      mask = np.zeros((H, W), dtype='float')
      value = 2 * pol - 1
    
      for xlim in [x0, x0 + 1]:
          for ylim in [y0, y0 + 1]:
              mask1 = (xlim < W) & (xlim >= 0) & (ylim < H) & (ylim >= 0)
              interp_weights = value * np.abs(1 - (xlim - x)) * np.abs(1 - (ylim - y))
              mask[y0[mask1], x0[mask1]] += interp_weights[mask1]
    
	  ## Here missing good mapping
      img[mask==0]=[255,255,255]
      img[mask==-1]=[255,0,0]
      img[mask==1]=[0,0,255]
      return img

**Comment by magehrig** [comment]
This should work for you:

```Python
def render_rect(x: np.ndarray, y: np.ndarray, pol: np.ndarray, t: np.ndarray, H: int, W: int) -> np.ndarray:
    x = x.squeeze()
    y = y.squeeze()
    pol = pol.squeeze()
    t = t.squeeze()
    assert x.size == y.size == pol.size
    assert H > 0
    assert W > 0
    img_acc = np.zeros((H,W), dtype='float32').ravel()

    pol = pol.astype('int')
    x0 = x.astype('int')
    y0 = y.astype('int')
    t = t.astype('float64')
    value = 2*pol - 1

    t_norm = (t - t.min())/(t.max() - t.min())
    t_norm = t_norm**2
    t_norm = t_norm.astype('float32')
    assert t_norm.min() >= 0
    assert t_norm.max() <= 1

    for xlim in [x0,x0+1]:
        for ylim in [y0,y0+1]:
            mask = (xlim < W) & (xlim >= 0) & (ylim < H) & (ylim >= 0)
            interp_weights = value * (1 - np.abs(xlim-x)) * (1 - np.abs(ylim-y)) * t_norm

            index = W * ylim.astype('int') + \
                    xlim.astype('int')

            np.add.at(img_acc, index[mask], interp_weights[mask])

    img_acc = np.reshape(img_acc, (H,W))

    img_out = np.full((H,W,3), fill_value=255,dtype='uint8')

    # Simple thresholding
    #img_out[img_acc > 0] = [0,0,255]
    #img_out[img_acc < 0] = [255,0,0]

    # With weighting (more complicated alternative)
    clip_percentile = 80
    min_percentile = -np.percentile(np.abs(img_acc[img_acc < 0]), clip_percentile)
    max_percentile = np.percentile(np.abs(img_acc[img_acc > 0]), clip_percentile)
    img_acc = np.clip(img_acc, min_percentile, max_percentile)


    img_acc_max = img_acc.max()
    idx_pos = img_acc > 0
    img_acc[idx_pos] = img_acc[idx_pos]/img_acc_max
    val_pos = img_acc[idx_pos]
    img_out[idx_pos] = np.stack((255-val_pos*255, 255-val_pos*255, np.ones_like(val_pos)*255), axis=1)

    img_acc_min = img_acc.min()
    idx_neg = img_acc < 0
    img_acc[idx_neg] = img_acc[idx_neg]/img_acc_min
    val_neg = img_acc[idx_neg]
    img_out[idx_neg] = np.stack((np.ones_like(val_neg)*255, 255-val_neg*255, 255-val_neg*255), axis=1)
    return img_out
```

Sometimes you still see the effects of rectification and forward warping but it is less visible.

It is up to you how you want to visualize events. There is no right or wrong. If you really care about removing rectification artefacts from the visualization you should use backward warping as mentioned above.

**Comment by ckrsls** [comment]
Hi @magehrig ,
thanks for your help, this works great!
![000001](https://user-images.githubusercontent.com/99343978/166688751-87746fda-4feb-4e89-8a2a-7c3e330281ac.png)
