### ISSUE TITLE
Camera biases

### ISSUE THREAD

**Issue by Tobias-Fischer** [uzh-rpg/DSEC#17]
Hi @magehrig,
Many thanks for your cool work and making the dataset available publicly! I would like to ask whether you can share the camera parameter settings for the different conditions? In the paper you state that the settings differ between daytime and nighttime, it would be great to share the biases; I'd like to collect some of my own data with the same camera and it would be nice if the data are comparable between the datasets.

Many thanks,
Tobias

**Comment by magehrig** [comment]
Hi Tobias

I am on vacation for two weeks and cannot access the files until I am back. I remember that we mainly adapted the contrast sensitivity. For night drives we set the value to 70. Then 73 for twilight and 77 for day drives.

Hope that helps

Best
Mathias

**Comment by Tobias-Fischer** [comment]
Great, thanks Mathias and enjoy your holidays!

**Comment by magehrig** [comment]
@Tobias-Fischer I sent you an email with the bias files.

For anyone else interested in the bias files, send me an email: mgehrig@ifi.uzh.ch

**Comment by Tobias-Fischer** [comment]
Many thanks @magehrig, I highly appreciate that!
