### ISSUE TITLE
HDF5 packager

### ISSUE THREAD

**Issue by fedepare** [uzh-rpg/DSEC#18]
Hi @magehrig,

The reason for this issue is that I would like to ask you whether you are planning to share the HDF5 packager (or details of it) that you used for this dataset. I've been playing around with it a little bit, and if I try to encode event data from your sequences using int16 for location, bool for polarity, and float64 for timestamps, the files becomes 4x bigger than yours. I also tried playing around with some other variable types, but never got close to your file size. This makes me think that there is a substantial difference between our packagers, as yours is significantly more efficient in terms of memory.

Thanks making the dataset publicly available and congrats on your recent work!

Best,
Federico Paredes-Valles

**Comment by magehrig** [comment]
Hi Federico

The difference is probably that I am using zstd compression (lzhc is also great). I am not planning to share that code openly as it is not in a state in which that makes sense. But I can share it privately with you when I am back in the office next week. Just drop me an email if you are interested.

Cheers

**Comment by fedepare** [comment]
Hi Mathias,

As you suggested, zstd compression for HDF5 makes a big difference in terms of the resulting file size. Thanks for letting me know about this!

Cheers,
Fede
