### ISSUE TITLE
Do you have the payload specs?

### ISSUE THREAD

**Issue by jaydeshpande** [uzh-rpg/DSEC#2]
Hi, 

Just saw the readme with the sensor suite. Do you have sensor suite specs? Also, are you planning to opensource the data collection programs that go with the sensor package?

**Comment by magehrig** [comment]
Hi

I can give you the details about the sensors. Regarding data collection: We used the spinnaker SDK for FLIR cameras and ROS driver for the Velodyne, both available online. For GPS and event camera we are using proprietary software so we cannot share it.

![image](https://user-images.githubusercontent.com/6841681/99057449-15744780-259c-11eb-936a-889d986974b6.png)

**Comment by magehrig** [comment]
This information is now available in the paper: http://rpg.ifi.uzh.ch/docs/RAL21_DSEC.pdf
