### ISSUE TITLE
Align DVS events in APS frame

### ISSUE THREAD

**Issue by jpzhong** [uzh-rpg/DSEC#21]
According to the `readme`, I am assuming that in order to align the events from event camera left to rectified frame camera left (resized to 640x480), I need to first use `T_01` and then use `R_rect0` in the `cam_to_cam.yaml`.
```
events = event_slicer.get_events(t_end_us - 5E4, t_end_us)
p = events['p']
x = events['x']
y = events['y']
t = events['t']
coords_4d = np.stack((x, y, np.ones_like(x), np.ones_like(x)))
evt_coord_in_aps = np.matmul(t_01, coords_4d)
evt_coord_rected = np.matmul(r_rect0, evt_coord_in_aps[:3, :])
```
where `t_end_us` is retrieved from `image_timestamps.txt` for the corresponding APS frame.

However, when I try to render the events on image, (replacing the empty image with the resized APS frame in the render() function in [scripts/events_to_video.py](https://github.com/uzh-rpg/DSEC/blob/6f62d95cd36218557173c2334559c0f3ac2986c0/scripts/events_to_video.py), the events do not align with the image edges. I'm not sure what I did wrong here.

P.S. there is a bug in render() on generating the masks, I believe. It should be
```
mask1 = (x >= 0) & (y >= 0) & (x < h) & (y < w)
mask[y[mask1], x[mask1]] = p[mask1]
```

An example of frame `000001.png` in sequence `zurich_city_04_e`
![img_nn](https://user-images.githubusercontent.com/10571143/128778851-50489d6d-2cdc-44be-9cfc-66214c476538.png)

**Comment by jpzhong** [comment]
Sorry It was a stupid question. The transformation should be about the 3D coordinates, not 2D.

**Comment by magehrig** [comment]
@jpzhong Thanks for the bug hint. It actually does not matter since the mask is true for all events anyway but I adapted it for the sake of correctness.

**Comment by UtharaKeerthan** [comment]
Hi, I also have a similar images from the events and frames. Please find the attached image. Could you please let me know what transformations you did on the event or image co ordinates to get the aligned events and the images ?
![rectified_events](https://user-images.githubusercontent.com/49371846/139672027-0ced9e91-b0ea-494e-825a-d9f14a300075.PNG)
