### ISSUE TITLE
Lidar data

### ISSUE THREAD

**Issue by nkliuhui** [uzh-rpg/DSEC#22]
Thanks for your open source work. Can you tell me whether the corresponding lidar data in the data set is open source? I can't find it on the website. I'm looking forward to your reply!

**Comment by magehrig** [comment]
Hi @nkliuhui 

We have not made it openly accessible. What is your intended use case (if you want to share that)?

**Comment by nkliuhui** [comment]
I want to use it to verify some multi-sensor fusion localization algorithms, like lidar-stereo-imu. I found some scenes different from other data sets, such as tunnels.

**Comment by nkliuhui** [comment]
And thanks for your reply!

**Comment by magehrig** [comment]
Currently, I don't have time to prepare a clean release of this data. Just drop me an email and let me know for which sequences you would like to have the data and I should be able to make it available to you. Does that sound good?

**Comment by nkliuhui** [comment]
Thanks for your sharing! ●▽●

**Comment by magehrig** [comment]
Should anyone have a similar request, please write me an email.

**Comment by cuimyue** [comment]
Hello, i am a PHD student from SYSU China. I also want the lidar data for verifying the performance of a multi-sensor fusion method.  could you please send to me cuimy@mail2.sysu.edu.cn?  Thank you !

**Comment by Renatusphere** [comment]
Hello, i am a PHD student from WHU China. I also want the lidar data for building a multi-sensor fusion mapping algorithm. Could you please send the lidar data of zurich_city_04_a and interlaken_00_d to me [lvchenwei@whu.edu.cn](mailto:lvchenwei@whu.edu.cn)? Thank you !

**Comment by xhlinxm** [comment]
Hello, i am a PHD student from XMU China. I also want the LiDAR data for development  some multi-sensor fusion method. Could you please send LiDAR data to me  xhlinxm@stu.xmu.edu.cn ？ 
If the complete data set is too large, you can provide some typical sequences first. Since LiDAR is the most commonly used sensor in automatic driving scenarios, I hope you can add LiDAR data to DSEC in the future. We look forward to your follow-up research results, Thank you !

**Comment by gkckdtn126** [comment]
Hello, i’m a Master student from unist, i also want the lidar point data for development some 3d reconstruction, could you please send lidar dada to gkckdtn126@unist.ac.kr?
Thank you!

**Comment by xuanforme** [comment]
Hello, I also want the lidar data for labeling 3D bounding box. could you please send to me ? xuanforme@yahoo.com.tw ? Thank you !

**Comment by magehrig** [comment]
The data is now available on the download page: https://dsec.ifi.uzh.ch/dsec-datasets/download/
