### ISSUE TITLE
Baseline implementation details

### ISSUE THREAD

**Issue by GEN418** [uzh-rpg/DSEC#26]
Hi Mathias,

First of all, thank you for your excellent work!
As described in DSEC dataset paper, you use voxel grid events representation to replace the event queues, I want to know the exact number of voxel grid bins and whether the DDES embedding module (Continuous fully-connected layer) are used.

Looking forward to your reply.

**Comment by magehrig** [comment]
Hi @GEN418, the experimental results reported in the paper is with 15 bins voxel grid (trilinear interpolation) + [PDS](https://github.com/tlkvstepan/PracticalDeepStereo_NIPS2018) network.
Does that answer your question?

**Comment by GEN418** [comment]
Yes, thank you very much.
