### ISSUE TITLE
Event frequency

### ISSUE THREAD

**Issue by UtharaKeerthan** [uzh-rpg/DSEC#28]
Hi, 
I have a question regarding the frequency at which the events are recorded. 
The document says that @ 20 Hz the frames are triggered and the stream of events are received at 20Hz. May I know what is the minimum time resolution to record 1 event?
Thanks in advance.

**Comment by magehrig** [comment]
Hi @UtharaKeerthan,

Events are continuously recorded and have a timestamp resolution of 1 microsecond.
This does not mean that the accuracy of the event is also 1 microsecond.
You can assume that in bright daylight, the latency of events is in the order of around 200 microseconds for the event camera that we used. Just a rough guess, I don't know the exact number.

**Comment by UtharaKeerthan** [comment]
Thanks a lot for the explanation.
