### ISSUE TITLE
Unable to read h5 event data

### ISSUE THREAD

**Issue by ahadviger** [uzh-rpg/DSEC#3]
Hello,

I am having issues with accessing data in the events.h5 files. I am using the fresh Anaconda environment as per your instructions provided in the readme with all dependencies installed properly. Here is the Python code snippet:
```
import h5py
import numpy as np
import tables as tb

filename = "/home/antea/datasets/dsec/events.h5"

h5f = h5py.File(filename, "r")
events = dict()

for dset_str in ['p', 'x', 'y', 't']:
  events[dset_str] = h5f['events/{}'.format(dset_str)]
 
print(events['x'])
print(events['x'][0])
```

and here is the output I get:

```
<HDF5 dataset "x": shape (129563187,), type "<u2">
Traceback (most recent call last):
  File "h5.py", line 14, in <module>
    print(events['x'][0])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/antea/.local/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 790, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 192, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 112, in h5py._proxy.dset_rw
  OSError: Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)
```

Basically, I can access all the information about the dataset (shape, type, etc.), but I can't read the actual data. Do you have any idea what might be the problem? I am not facing this issue when reading the rectify_map.h5 files, only the events.

Thanks,
Antea

**Comment by magehrig** [comment]
Instead of importing tables, you can install the blosc-hdf5 plugin. That should solve the problem:

`conda install -c conda-forge blosc-hdf5-plugin`

Let me know if that resolves this issue.

**Comment by magehrig** [comment]
Updated the documentation and code which resolves this issue

**Comment by ahadviger** [comment]
Thank you, @magehrig, this resolved it!

**Comment by RunqiuBao** [comment]
FYI, adding 'import hdf5plugin' also solved the issue.

**Comment by Ethan-Zhou** [comment]
> import hdf5plugin

This one save my day!

**Comment by SkYiMlTo** [comment]
> FYI, adding 'import hdf5plugin' also solved the issue.

Saved me today, thanks!
