### ISSUE TITLE
mapping between event frames and RGB frames

### ISSUE THREAD

**Issue by wshku** [uzh-rpg/DSEC#33]
Hi,

I notice the code https://github.com/uzh-rpg/DSEC/issues/25#issuecomment-956491275 you provided that generates event frames (640x480) from RGB frames (1440x1080). The mapping in the code could get the positions of the points of event frames in RGB frames.  I am wondering whether you could provide the mappings by which we could get the positions of the points of RGB frames in event frames. Thank you so much

**Comment by magehrig** [comment]
Hi @wshku 

The code you linked in your response actually does what you are asking for: It warps the image of the left global shutter camera to the left event camera frame.

**Comment by magehrig** [comment]
@wshku if my answer solves your issue, please close the issue. Otherwise, let me know
