### ISSUE TITLE
Requesting for IMU data

### ISSUE THREAD

**Issue by UtharaKeerthan** [uzh-rpg/DSEC#34]
Hi,

I'm working on visual inertial odometry on the DSEC dataset. May I have the IMU data (linear linear_acceleration and angular velocity)for all the sequences under zurich_city_04 and also the calibration parameters for the Transformation matrix between all the cameras and the IMU device? Thanks in advance.

**Comment by magehrig** [comment]
The data is now avaible on the download page: https://dsec.ifi.uzh.ch/dsec-datasets/download/
