### ISSUE TITLE
Requesting for ground truth depth image

### ISSUE THREAD

**Issue by wang-zixuan** [uzh-rpg/DSEC#35]
Hi! I am working on event stereo to estimate depth from the scenario. Since the dataset only provides ground truth disparity maps, may I have the ground truth depth images for all the sequences? Or, can I know the parameter of focal length and baseline so that I can generate depth from disparity? Thanks!

**Comment by magehrig** [comment]
Hey @wang-zixuan 

You can find the calibration files for each sequence on the download webpage: https://dsec.ifi.uzh.ch/dsec-datasets/download/
The description on how to convert disparity to depth is at the bottom of this page: https://dsec.ifi.uzh.ch/data-format/
