### ISSUE TITLE
AssertionError: Unknown encoder extension: 

### ISSUE THREAD

**Issue by aelmoudni** [uzh-rpg/DSEC#38]
Hi everyone, 

It's my first attempt  with DSEC data set, i'm trying to visualize the event file, but i keep on finding the same error, i checked in some forums and found that problem came from the instalation of ffmpeg, as far as i can tell, it's well installed on my Macos 
 & ubuntu machines , do you have any advices ?

**Comment by magehrig** [comment]
I cannot help with fixing this. What you can do instead is write the images to disk and create a video from the images in a post-processing step (e.g. in the command line using ffmpeg or another tool).

**Comment by aelmoudni** [comment]
Thanks for your answer, i understand, i am just trying to visualize the data for now, and i will try and do depth estimation on the DSEC dataset, i will try and do what you have said and comeback to you.

**Comment by aelmoudni** [comment]
Hello,

Yes you can close it, I found a solution.
I appreciate your reactivity.

Sincerely yours,

Anass

Le lun. 25 avr. 2022 à 17:24, Mathias Gehrig ***@***.***> a
écrit :

**Comment by magehrig** [comment]
If you can, please post the solution here so others benefit from it too
