### ISSUE TITLE
How to match events timestamps and disparity maps timestamps

### ISSUE THREAD

**Issue by GEN418** [uzh-rpg/DSEC#4]
Hello,

I notice that the timestamps of events are relative time, but the timestamps of disparity maps are ROS time, so what is the relationship between them.

**Comment by magehrig** [comment]
The event timestamps have a dataset group called `t_offset` which must be added to the event timestamps. This is done to enable uint32 timestamps for the events. I will update the documentation in the next few days

**Comment by GEN418** [comment]
I found it, thank you

**Comment by magehrig** [comment]
Updated documentation and code which resolves this issue
