### ISSUE TITLE
Wrong Compression in Docs

### ISSUE THREAD

**Issue by klowrey** [uzh-rpg/DSEC#42]
The docs say that the hdf5 files are compressed with zstd. This is incorrect, at least for interlaken_00_c's left event stream.

```bash
$ h5dump -pH events.h5 | grep 'FILTER\|COMMENT'
         FILTERS {
            USER_DEFINED_FILTER {
               FILTER_ID 32001
               COMMENT blosc
         FILTERS {
            USER_DEFINED_FILTER {
               FILTER_ID 32001
               COMMENT blosc
         FILTERS {
            USER_DEFINED_FILTER {
               FILTER_ID 32001
               COMMENT blosc
         FILTERS {
            USER_DEFINED_FILTER {
               FILTER_ID 32001
               COMMENT blosc
      FILTERS {
         USER_DEFINED_FILTER {
            FILTER_ID 32001
            COMMENT blosc
      FILTERS {
```

This might be critical for folks that want to access such data. Either the documentation should be change or the files re-compressed and uploaded.

**Comment by magehrig** [comment]
Thanks for the feedback. I updated the [docs](https://dsec.ifi.uzh.ch/data-format/) to reflect that Blosc is used with the ZSTD codec. Let me know if you think it is clear now or if something is missing.
