### ISSUE TITLE
If detailed evaluation result for each sequnce available on disparity benchmark?

### ISSUE THREAD

**Issue by HTLeoo** [uzh-rpg/DSEC#45]
Hi, Mathias
I want to know if the detailed evaluation result for each sequnce on disparity benchmark is available. I notice that you publish the evaluation result in terms of city. While on optical flow benchmark, you publish the detailed result for each sequence.

**Comment by magehrig** [comment]
Hi @HTLeoo 
Unfortunately, it is not available for the disparity benchmark. The optical flow evaluation script is different from the disparity evaluation script. At this point, I cannot change the underlying script anymore.
