### ISSUE TITLE
DSEC website is down

### ISSUE THREAD

**Issue by fedepare** [uzh-rpg/DSEC#48]
Hi Mathias,

The DSEC website (dsec.ifi.uzh.ch) seems to be down. Could you have a look at it when you have some time?

Thanks in advance!
Federico Paredes-Valles

**Comment by fedepare** [comment]
It's back online again. Closing this issue.

Thanks!

**Comment by magehrig** [comment]
There is/was a cyberattack against our University such that the IT decided to restrict access to all university-related services (including DSEC) to Switzerland. It might be the case that they have opened the network for Europe, but some people in China might still not have access, not sure. I hope the situation gets resolved soon!

**Comment by magehrig** [comment]
@yilun-wu Thanks, looking into it.
