### ISSUE TITLE
Can not access to the benchmark website

### ISSUE THREAD

**Issue by eugenelyj** [uzh-rpg/DSEC#49]
@magehrig Hi, I find that the [website](https://dsec.ifi.uzh.ch/dsec-datasets/download/) can not be accessed these days. Please check the web server.

**Comment by magehrig** [comment]
Hi @eugenelyj 

Same issue but it appears that some countries have access already. I hope the situation gets resolved soon!
https://github.com/uzh-rpg/DSEC/issues/48

**Comment by magehrig** [comment]
As of now, a workaround is to use VPN to one of the following countries: Switzerland, Austria, Germany or Netherlands.

**Comment by eugenelyj** [comment]
@magehrig Hi, is it possible to deploy the service on the public cloud server like google?

**Comment by magehrig** [comment]
We are not planning to deploy the service on a public cloud server

**Comment by eugenelyj** [comment]
Now it seems that you can access the website without a VPN :)

**Comment by eugenelyj** [comment]
Hi, there is a new problem "Error establishing a database connection" when i open the website.
@magehrig Could you check the website?

**Comment by magehrig** [comment]
@eugenelyj Thanks we are looking into it. It looks like the server hosting the website crashed.

**Comment by magehrig** [comment]
The website is up and running again
