### ISSUE TITLE
A question about the depth maps of the test dataset of your paper

### ISSUE THREAD

**Issue by LLHEVER** [uzh-rpg/DSEC#52]
Hello author, Thank you for your wonderful work!
Here I want to konw could you share your depth maps on the test dataset of your paper.
I'd appreciated if you can share the results!

**Comment by magehrig** [comment]
Hi @LLHEVER 

Thank you for your kind words and interest in our work!

Regarding your request for the depth maps on the test dataset, we have set up an automatic evaluation server that uses these depth maps to run a benchmark. Due to this setup, we do not make the depth maps publicly available.

**Comment by LLHEVER** [comment]
Hi @magehrig

Thank you for your reply!

However, I think you misunderstood my meaning, I want the inference results of DDES on DSEC data set mentioned in your paper, but not the ground truth of the test set.

**Comment by LLHEVER** [comment]
Hi @magehrig

I'm sorry for replying so late

my email is (nanqiworker@gmail.com)

**Comment by magehrig** [comment]
Done

**Comment by LLHEVER** [comment]
Ok, thank you very much!
