### ISSUE TITLE
RGB and Optical Flow Resolutions

### ISSUE THREAD

**Issue by Alkaponn** [uzh-rpg/DSEC#53]
Hi, I want to test some RGB Optical Flow models on DSEC. How should I map 1440x1080 images to 640x480 Optical Flows?

**Comment by magehrig** [comment]
The easiest way is to map the images from the left video camera to the left event camera. There are two approaches:
1) You map the images by assuming that the baseline between the cameras is negligible for which you can use the code provided in the related issue: https://github.com/uzh-rpg/DSEC/issues/25 . One issue is that it will be less accurate for parts of the scene that are close to the cameras. On the other hand, it is very fast to compute.
2) You use a SOTA stereo method on the frame or event camera stereo pair and use this more accurate depth to map the images to the left event camera. This is more cumbersome but also more accurate.

Let me know if this answers your question

**Comment by Alkaponn** [comment]
Thanks a lot! At first I've tried to resize the images directly from 1440x1080 to 640x480. I'll try to use these approaches.
