### ISSUE TITLE
Question about the MVSEC

### ISSUE THREAD

**Issue by LLHEVER** [uzh-rpg/DSEC#55]
Thank you for your excellent work!

Now I'm working on depth estimation based on events and images.  
When I create the MVSEC dataset following the work "Learning an event sequence embedding for dense event-based deep stereo", I met some problems.
Therefore I want to know could you share the final file data?
![MVSEC](https://github.com/uzh-rpg/DSEC/assets/65348961/6e39620f-cad6-4cc2-aa0d-b4e4afa6329e)

Thank you very much!

**Comment by magehrig** [comment]
I suggest contacting the authors of the MVSEC dataset. This GitHub repo is about the DSEC dataset.

Thanks
