### ISSUE TITLE
How I can convert .h5 event files to txt format?

### ISSUE THREAD

**Issue by ramnamaqsood** [uzh-rpg/DSEC#56]
Hi,
Thanks for the great work, Can you please guide me how can I convert event files from .h5 format to txt format? Is it valid to do with this dataset? 

Thanks and regards,

**Comment by magehrig** [comment]
Thanks @ramnamaqsood

You can use [this code](https://github.com/uzh-rpg/DSEC/blob/17a4a0fb032644c3839812127b0ef5ae5cbdffa7/scripts/events_to_video.py#L27-L51) to read out x, y, p, and t and then write it into a txt file.

**Comment by ramnamaqsood** [comment]
@magehrig  Thank you very much for your response. I have modified the code to write data in txt file. Just for verification, I have shown few converted data. Can you please verify it? 

307	201	1	57922807588
568	201	1	57922807588
572	205	1	57922807588
549	205	1	57922807588
247	205	0	57922807588
233	204	0	57922807588
58	204	1	57922807588
424	204	1	57922807588
526	206	1	57922807588
225	206	1	57922807588
227	206	1	57922807588

**Comment by magehrig** [comment]
yes that seems reasonable

**Comment by stubborn111** [comment]
@ramnamaqsood hello，could you share your code that you used to convert .h5 event files to txt format ? I appreciate your support very much！

**Comment by xqdd333** [comment]
@ramnamaqsood  do you use ubuntu or windows？
