### ISSUE TITLE
Name of the file corresponding to the sequence driving through the tunnel

### ISSUE THREAD

**Issue by zhamaliddin-kalzhan** [uzh-rpg/DSEC#59]
Hello! 
Great work with the event-camera dataset!

I can't find the file corresponding to the sequence driving through the tunnel (middle picture of Figure 3 in the paper).
Can you give a hint what is the file name?

**Comment by magehrig** [comment]
Hi @zhamaliddin-kalzhan 

This is in interlaken_00_b
