### ISSUE TITLE
Depth completion

### ISSUE THREAD

**Issue by ciliverlee** [uzh-rpg/DSEC#60]
Hello!
Thank you for your excellent work.
I am  I am working on event stereo to estimate depth.Since the dataset only provides ground truth disparity maps needed completion, may I have the code which can complete them suitably or the completed ground truth?
Looking forward to your reply.Thanks again.

**Comment by magehrig** [comment]
Hi @ciliverlee 
There is no such algorithm that we use. We just provide the sparse/semi-dense ground truth

**Comment by ciliverlee** [comment]
Thank you for your answer.
