### ISSUE TITLE
Own benchmarking of optical flow

### ISSUE THREAD

**Issue by a-milans-del-bosch** [uzh-rpg/DSEC#62]
Hello, 
I am trying to compare several algorithms in different languages in my computer and i have been searching for some ground truth to calculate the desired metrics. I have checked you provide a ground truth for training algorithms, basically composed by images but i dont want to train my algorithms just test them. For this I was wondering if you have some kind of documentation on your database of the movement measurements such as: 
vx and vy - Speed in X and Y axis (maybe in in pixels per second) respectively in the image plane of the considered event(x,y,t,p)
Or maybe not for every event but for the testing or evaluation timestamps only. This would be enough. 
Thanks for your work!

**Comment by magehrig** [comment]
no, vx and vy is not available for DSEC Flow
