### ISSUE TITLE
Some image is broken after download

### ISSUE THREAD

**Issue by nhanlamtac** [uzh-rpg/DSEC#74]
The image in these location are error
/zurich_city_04_d/images/left/rectified/000205.png
/zurich_city_00_b/images/left/rectified/000089.png
/zurich_city_10_a/images/left/rectified/002035.png
![image](https://github.com/user-attachments/assets/e819ce34-d086-49d1-96ad-57969f6331e7)
Does anyone have the same issue? If possible, please send me these images, I am afraid that the result is the same if I download it again

**Comment by magehrig** [comment]
I cannot reproduce this issue. Just downloaded the dataset again and the images are looking ok to me (see screenshot attached). I suggest you re-download the dataset to be sure.

Example for /zurich_city_04_d/images/left/rectified/000205.png

![image](https://github.com/user-attachments/assets/3c70b77a-4939-428a-a6c1-7244a041cc51)
