### ISSUE TITLE
DSEC-det label wrong (x,y out of range)

### ISSUE THREAD

**Issue by 233AvavAvA** [uzh-rpg/DSEC#75]
![微信图片_20241206221110](https://github.com/user-attachments/assets/4cfe14f2-1e6d-4783-b8dd-2de4bb20a4a0)
from:train/zurich_city_16_a/object_detections/left/tracks.npy

**Comment by 233AvavAvA** [comment]
Thank you very much for your excellent work, but I found that this situation exists in both the train data and the test data labels, and there are many x,y coordinates less than 0. Can you tell me what is going on and what should I do?

**Comment by magehrig** [comment]
The appropriate page for this issue is: https://github.com/uzh-rpg/dsec-det/
