### ISSUE TITLE
Left and right event rectify maps swapped?

### ISSUE THREAD

**Issue by ahadviger** [uzh-rpg/DSEC#8]
Hello,

is it possible that rectification maps for events found in rectify_map.h5 are swapped between left and right event cameras? I tried multiple sequences from zurich_city_04 and get good rectification only when I swap the maps.

Thanks,
Antea

**Comment by magehrig** [comment]
Hi @ahadviger 

How did you verify whether the rectification is good or not? A quick sanity check on my side shows that it should be correct.

The following example is the rectified voxel grids (left and right) converted to images with epipolar lines (with the files as provided):
![image](https://user-images.githubusercontent.com/6841681/116437356-ac347800-a84d-11eb-90bf-9c1067fa42e2.png)
You can see that horizontally the match is accurate.

Now if I switch the rectification files I get this unaligned rectification:

![image](https://user-images.githubusercontent.com/6841681/116438075-62985d00-a84e-11eb-91d2-f97e64700b13.png)

**Comment by magehrig** [comment]
@ahadviger Let me know when you have updates and we can reopen this issue if necessary

**Comment by ahadviger** [comment]
Hi @magehrig, thank you very much for checking this, I must have made some random mistake with filenames or something like that, even though I checked everything multiple times before posting here. Sorry and thanks again!
