### ISSUE TITLE
Event undistortion

### ISSUE THREAD

**Issue by RunqiuBao** [uzh-rpg/DSEC#9]
Hello, I am looking at your great dataset.

I suppose the event raw data were not preprocessed with lens undistortion?
So I tried undistortion with the intrinsics you provided, but the result is a weird. seems like already undistorted before.
![image](https://user-images.githubusercontent.com/35663368/116633469-85cd2480-a994-11eb-9e60-53025991614b.png)

So just to make sure if you have already undistorted the events raw data?

Thanks!

**Comment by magehrig** [comment]
Hi @RunqiuBao 

According to the description in https://github.com/uzh-rpg/DSEC#rectification, events are saved as they arrive on the sensor (distorted). The `rectify_map.h5` that is provided with each event file can be used to undistort the events directly. You don't need to use the calibration files for that.
Hope that helps
